name: device_calendar
description: A cross platform plugin for modifying calendars on the user's device.
version: 4.2.1
homepage: https://github.com/builttoroam/device_calendar/tree/master

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.16.0

  timezone:
    git:
      url: git@github.com:Arcascope/timezone.git
      branch: ^0.9.4

  rrule: ^0.2.10
  flutter_native_timezone: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.builttoroam.devicecalendar
        pluginClass: DeviceCalendarPlugin
      ios:
        pluginClass: DeviceCalendarPlugin

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"
